app:
    #resource: '@AppBundle/Controller/'
    #type: annotation
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /admin

#backend:
#    resource: "@BackendBundle/Resources/config/routing.yml"
#    prefix:   /
