app_homepage:
    path: /
    #defaults: { _controller: AppBundle:User:login }
    defaults: { _controller: AppBundle:Admin:home }

app_admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix: /admin
